locales:
  pad:
    name: Paumarí Keyboards
    description: >-
      Mobile OS keyboards for the Paumarí language from the Divvun group
      at UiT.
  en:
    name: Paumarí Keyboards
    description: >-
      Mobile OS keyboards for the Paumarí language from the Divvun group
      at UiT.
  nb:
    name: Paumarí tastatur
    description: Mobiltastatur for Paumarí fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
